<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2017-09-07T14:08:53+02:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      api_keys.google.maps
 * @group     app
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'server_timezone' => 'Europe/Berlin',
    'api_keys' => [
        'google' => [
            'maps' => 'AIzaSyCPXtwFFjWx2L21oqkLmqM44eQlzBegtDA',
        ],
    ],
];
