<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2017-08-31T10:51:23+02:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      sites.default.seo.canonical_url_alternative
 * @group     site
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'sites' => [
        'default' => [
            'name' => 'Shop4c',
            'seo' => [
                'canonical_url' => '',
                'canonical_url_alternative' => '',
            ],
        ],
    ],
];
