<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2017-08-24T15:35:58+02:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      sites.default.name
 * @group     site
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'sites' => [
        'default' => [
            'name' => 'Shop4c',
        ],
    ],
];
